/// Generated file. Do not edit.
/// This file is generated by the iFlutter
library;

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'adchat';
  static const String PLUGIN_VERSION = '1.0.0';
  static const String AVATAR = 'assets/avatar.png';
  static const String BACKGROUNDIMAGE = 'assets/backgroundImage.png';
  static const String BG = 'assets/bg.png';
}
